config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  
  get 'contact' => 'pages#contact'

  resources :facts
  
  root 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end
background-color: blue;

app/models/fact.rb
class Fact < ApplicationRecord
    validates :body, presence: true, length: { maximum: 200, minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
  before_action :set_fact, only: [:show, :edit, :update, :destroy]

  # GET /facts
  # GET /facts.json
  def index
    @facts = Fact.all.reverse_order
  end

  # GET /facts/1
  # GET /facts/1.json
  def show
  end

  # GET /facts/new
  def new
    @fact = Fact.new
  end

  # GET /facts/1/edit
  def edit
  end

  # POST /facts
  # POST /facts.json
  def create
    @fact = Fact.new(fact_params)

    respond_to do |format|
      if @fact.save
        format.html { redirect_to @fact, notice: 'Fact was successfully created.' }
        format.json { render :show, status: :created, location: @fact }
      else
        format.html { render :new }
        format.json { render json: @fact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facts/1
  # PATCH/PUT /facts/1.json
  def update
    respond_to do |format|
      if @fact.update(fact_params)
        format.html { redirect_to @fact, notice: 'Fact was successfully updated.' }
        format.json { render :show, status: :ok, location: @fact }
      else
        format.html { render :edit }
        format.json { render json: @fact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facts/1
  # DELETE /facts/1.json
  def destroy
    @fact.destroy
    respond_to do |format|
      format.html { redirect_to facts_url, notice: 'Fact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fact
      @fact = Fact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fact_params
      params.require(:fact).permit(:body, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/facts/_form.html.erb
<%= form_with(model: fact, local: true) do |form| %>
  <% if fact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fact.errors.count, "error") %> prohibited this fact from being saved:</h2>

      <ul>
      <% fact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :fact_body %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :fact_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/facts/edit.html.erb
<h1>Editing Fact</h1>

<%= render 'form', fact: @fact %>

<%= link_to 'Show', @fact %> |
<%= link_to 'Back', facts_path %>

app/views/facts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>trollpedia</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @facts.each do |fact| %>
      <div style="max-width: 300px">
        <td>hello!:):<%= fact.body %></td>
        <td><%= image_tag fact.image, style: "max-width: 500px; max-height: 500px"; %></td>
        <td><%= link_to 'look', fact %></td>
        <td><%= link_to 'edit', edit_fact_path(fact) %></td>
        <td><%= link_to 'burn', fact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fact', new_fact_path %>

app/views/facts/new.html.erb
<h1>New Fact</h1>

<%= render 'form', fact: @fact %>

<%= link_to 'Back', facts_path %>

app/views/facts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @fact.body %>
</p>

<p>
  <strong>Image:</strong>
  <%= @fact.image %>
</p>

<%= link_to 'Edit', edit_fact_path(@fact) %> |
<%= link_to 'Back', facts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facts</title>
    <link href="https://fonts.googleapis.com/css?family=Artifika" rel="stylesheet">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/contact.html.erb
<h1>Contact page</h1>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>